name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            cpp_compiler: cl
            version: '14'
          - os: ubuntu-latest
            cpp_compiler: g++
            version: '18'
          - os: macos-latest
            cpp_compiler: clang++
            version: 'latest'

    steps:
    - uses: actions/checkout@v6

    # Setup GCC for Linux
    - name: Setup GCC
      if: matrix.compiler == 'gcc'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.version }}

    # Setup Clang for macOS
    - name: Setup Clang
      if: matrix.compiler == 'clang'
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.version }}

    - name: Set reusable strings
      # Turn these into environment variables for shorter commands
      id: strings
      shell: bash
      run: >
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: >
        cmake --build ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}

    - name: Test
      run: >
        ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}
        -C ${{ matrix.build_type }} --output-on-failure
